import { createServer } from 'vite';
import { chromium } from 'playwright';
import fs from 'node:fs';
const server = await createServer({ server: { port: 4312, strictPort: true } });
await server.listen();
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const page = await browser.newPage();
page.on('pageerror', (e) => console.error('pageerror:', e));
page.on('console', (m) => { if (m.type() === 'error') console.error('console:', m.text()); });
await page.goto('http://localhost:4312/tools/animalconvert.html');
await page.waitForFunction(() => !!window.__result, undefined, { timeout: 600000 });
const { report, shots, glb } = JSON.parse(await page.evaluate(() => window.__result));
fs.writeFileSync('public/models/animals.glb', Buffer.from(glb, 'base64'));
for (const [id, b64] of Object.entries(shots)) fs.writeFileSync(`scratch-animal-${id}.png`, Buffer.from(b64, 'base64'));
console.log('animals.glb', Math.round(Buffer.from(glb, 'base64').length / 1024), 'KB');
console.log(JSON.stringify(report));
await browser.close();
await server.close();
process.exit(0);
