import { createServer } from 'vite';
import { chromium } from 'playwright';
const server = await createServer({ server: { port: 4316, strictPort: true } });
await server.listen();
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const page = await browser.newPage();
page.on('pageerror', (e) => console.error('pageerror:', e));
await page.goto('http://localhost:4316/tools/treeanalyze.html');
await page.waitForFunction(() => !!window.__result, undefined, { timeout: 600000 });
console.log(await page.evaluate(() => window.__result));
await browser.close(); await server.close(); process.exit(0);
